name: CardManager
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "com.imthiago"
targets:
  CardManager:
    type: application
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManager
    dependencies:
      - target: CardManagerDomain
      - target: CardManagerInfrastructure
      - target: CardManagerPresentation
      - target: CardManagerApplication
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManager-iOS-Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerTests
    dependencies:
      - target: CardManager
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManager-iOS-UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CardManagerUITests
    dependencies:
      - target: CardManager
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerDomain:
    type: framework
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerDomain
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerDomainTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerDomainTests
    dependencies:
      - target: CardManagerDomain
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerPresentation:
    type: framework
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerPresentation
    dependencies:
      - target: CardManagerApplication
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerPresentationTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerPresentationTests
    dependencies:
      - target: CardManagerPresentation
      - target: CardManagerApplication
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerApplication:
    type: framework
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerApplication
    dependencies:
      - target: CardManagerInfrastructure
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerInfrastructure:
    type: framework
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerInfrastructure
    dependencies:
      - target: CardManagerDomain
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
  CardManagerInfrastructureTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: CardManagerInfrastructureTests
    dependencies:
      - target: CardManagerInfrastructure
      - target: CardManagerDomain
    postCompileScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Swiftlint
